import 'dart:convert';

import 'package:apilive/apidata2.dart';
import 'package:dio/dio.dart';

Future<Autogenerated> getHttp1() async {
  try {
    var response = await Dio().get(
      'https://newsapi.org/v2/top-headlines?country=in&category=health&apiKey=e11d59c3734246baa947ba3667526993',
    );
    if (response.statusCode == 200) {
      var temp = autogenratedFromJson(json.encode(response.data));
      print(temp);
      print('response is correct');
      return temp;
    } else {
      //print('Errorrrrrrrrr');
    }
    return Autogenerated();
  } catch (e) {
    //print(e);
    return Autogenerated();
  }
}
