import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:apilive/apidata2.dart';
import 'package:dio/dio.dart';

Future<Autogenerated> getHttp1() async {
  var response = await http.get(Uri.parse(
      'https://newsapi.org/v2/top-headlines?country=in&category=health&apiKey=e11d59c3734246baa947ba3667526993'));
  print(response);
  if (response.statusCode == 200) {
    return Autogenerated.fromJson(json.decode(response.body));
  } else {
    throw Exception('Failed to load News');
  }
}
