import 'dart:convert';

/*Autogenerated autogenratedFromJson(String str) =>
    Autogenerated.fromJson(json.decode(str));*/

class Autogenerated {
  Autogenerated({
    this.articles,
  });
  List<Articles> articles;

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
        articles: List<Articles>.from(
            json["articles"].map((x) => Articles.fromJson(x))),
      );
}

class Articles {
  Articles(
      {this.source,
      this.author,
      this.title,
      this.description,
      this.url,
      this.urlToImage,
      this.publishedAt,
      this.content});

  String source;
  String author;
  String title;
  String description;
  String url;
  String urlToImage;
  String publishedAt;
  String content;

  factory Articles.fromJson(Map<String, dynamic> json) => Articles(
        source: json['source'].toString(),
        author: json['author'].toString(),
        title: json['title'].toString(),
        description: json['description'].toString(),
        url: json['url'].toString(),
        urlToImage: json['urlToImage'].toString(),
        publishedAt: json['publishedAt'].toString(),
        content: json['content'].toString(),
      );
}
